version: '3.8'
services:
  web:
    container_name: web
    build:      
      context: ./
      # dockerfile: ./HelloDockerWeb/Dockerfile
    depends_on: [ db ]
    ports:
      - "8080:80"
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=asdasd
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local