version: '3.5'

services:
  asp:
    container_name: 'web'
    restart: always
    build:      
        context: ./
        # dockerfile: ./HelloDockerWeb/Dockerfile
    #environment:
        #- DB_CONNECTION_STRING=Host=postgres;Database=test;Username=test;Password=test      
        #- "ConnectionStrings:WebApiDatabase=Host=postgres;Database=test;Username=test;Password=test"      
    depends_on: 
        - "postgres"
    #command: dotnet watch --project ./app run --urls "http://0.0.0.0:80"
    ports:
        - "3000:80"
        #- "443:443"
    networks:
      - main-network

  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-test}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
      # PGDATA: /data/postgres
    #volumes:
    #   - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - main-network
    restart: unless-stopped
  

  #pgadmin:
  #  container_name: pgadmin
  #  image: dpage/pgadmin4
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #    PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #    PGADMIN_CONFIG_SERVER_MODE: 'False'
  #  volumes:
  #     - pgadmin:/var/lib/pgadmin

  #  ports:
  #    - "${PGADMIN_PORT:-8080}:80"
  #  networks:
  #    - main-network
  #  restart: unless-stopped



networks:
  main-network:
    driver: bridge

#volumes:
#    postgres:
    #pgadmin: