version: '3.8'
services:
  web:
    container_name: web
    build:      
      context: ./
      # dockerfile: ./HelloDockerWeb/Dockerfile
    depends_on: [ db ]
    ports:
      - "3000:80"
  db:
    container_name: pgsql
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-test}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
      # PGDATA: /data/postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local